apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: kubeai-project
build:
  artifacts:
  - image: substratusai/kubeai
    # NOTE: If you run into this error:
    #
    # Checking cache...
    #  - substratusai/kubeai: Error checking cache.
    # getting hash for artifact "substratusai/kubeai": getting dependencies for "substratusai/kubeai": parsing ONBUILD instructions: retrieving image "gcr.io/distroless/static:nonroot": GET https://gcr.io/v2/token?scope=repository%3Adistroless%2Fstatic%3Apull&service=gcr.io: UNAUTHORIZED: authentication failed
    #
    # Then run "docker pull gcr.io/distroless/static:nonroot" and retry.
    # Disabling cache for the image that uses distroless/static:nonroot does not appear to work:
    #
    # docker:
    #   noCache: true
    #
  local:
    push: false
      # Needed for preventing gcloud auth error even when GCR isn't used.
      # Reference: https://github.com/GoogleContainerTools/skaffold/issues/9336#issuecomment-2105523768
      useBuildkit: true
deploy:
  helm:
    releases:
    - name: kubeai
      chartPath: ./charts/kubeai
portForward:
- resourceType: service
  resourceName: kubeai
  namespace: default
  port: 80
  localPort: 8000

profiles:
- name: kubeai-only
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        setValueTemplates:
          openwebui.enabled: false

- name: kubeai-only-gke
  build:
    local:
      push: true
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        setValueTemplates:
          openwebui.enabled: false
        valuesFiles:
        - ./charts/kubeai/values-gke.yaml

- name: e2e-test-default
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        valuesFiles:
        - ./test/e2e/common-values.yaml
        setValueTemplates:
          openwebui.enabled: false
- name: e2e-test-gpu
  build:
    local:
      push: true
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        valuesFiles:
        - ./charts/kubeai/values-nvidia-k8s-device-plugin.yaml
        setValueTemplates:
          openwebui.enabled: false
- name: e2e-test-autoscaler-restart
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        valuesFiles:
        - ./test/e2e/common-values.yaml
        setValueTemplates:
          openwebui.enabled: false
          modelAutoscaling.interval: 1s
          modelAutoscaling.timeWindow: 30s
- name: e2e-test-engine
  deploy:
    helm:
      releases:
      - name: kubeai
        chartPath: ./charts/kubeai
        valuesFiles:
        - ./test/e2e/common-values.yaml
        setValueTemplates:
          openwebui.enabled: false
