# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: deepseek-r1-distill-qwen-1.5b-rtx4070
spec:
  features: [TextGeneration]
  url: hf://deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  engine: VLLM
  args:
    - --max-model-len=2048
    - --max-num-batched-token=2048
    - --max-num-seqs=8
    - --kv-cache-dtype=fp8
  env:
    VLLM_USE_V1: "1"
  minReplicas: 0
  resourceProfile: nvidia-gpu-rtx4070-8gb:1
