apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubeai-vllm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  podMetricsEndpoints:
  - port: http
  - interval: 2s
